### PR TITLE
Error sending snoop msg on media messages

### PR DESCRIPTION
**Pull request by giuseppeM99**
While a media message is send, the "text" variable is nil and gives an error that block the execution of the antispam/antiflood plugin

added an exeption for that

### CODE REVIEW

**Comment by LucentW** [comment]
@giuseppeM99 This doesn't really fix the issue on the antispam plugin. Will fix that ASAP, thanks for the feedback anyways.

**Comment by giuseppeM99** [comment]
@LucentW at least, flooders and spammer will be kicked

**Comment by LucentW** [comment]
Fixed by eafb46ef34d8b2e3131a781b31deb04329f45752.
It solves also the fact that images/GIFs/files captions weren't treated as message text.

**Comment by veetaw** [comment]
@LucentW Test

**Pull request closed without merging**
